default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    ipa_path = ENV["FASTLANE_IPA_PATH"]

    deliver(
      ipa: ipa_path,
      app_identifier: "com.alanjay.alanjayfleet",   # ← EXACTLY this string
      skip_metadata:  true,
      skip_screenshots: true,
      submit_for_review: false
    )
  end
end
